### ISSUE TITLE
Remove ComponentStatus deprecated warnings

### ISSUE THREAD

**Issue by ipochi** [kinvolk/lokomotive#1414] opened 2021-03-04 05:40 UTC
When doing a `lokoctl health`, there is a warning message from `client-go` that ComponentStatus is deprecated in v1.19+.

This doesn't look nice for UX point of view and should not be present in the output

example output
```
core@kin-swp6s2 ~/lokomotive $ lokoctl health

Node                       Ready    Reason          Message

lokomotive-worker-13       True     KubeletReady    kubelet is posting ready status
lokomotive-worker-22       True     KubeletReady    kubelet is posting ready status
lokomotive-worker-9        True     KubeletReady    kubelet is posting ready status
lokomotive-worker-1        True     KubeletReady    kubelet is posting ready status
lokomotive-worker-15       True     KubeletReady    kubelet is posting ready status
lokomotive-worker-3        True     KubeletReady    kubelet is posting ready status
lokomotive-worker-19       True     KubeletReady    kubelet is posting ready status
lokomotive-worker-12       True     KubeletReady    kubelet is posting ready status
lokomotive-worker-16       True     KubeletReady    kubelet is posting ready status
lokomotive-worker-17       True     KubeletReady    kubelet is posting ready status
lokomotive-worker-18       True     KubeletReady    kubelet is posting ready status
lokomotive-worker-28       True     KubeletReady    kubelet is posting ready status
lokomotive-worker-30       True     KubeletReady    kubelet is posting ready status
lokomotive-worker-31       True     KubeletReady    kubelet is posting ready status
lokomotive-worker-6        True     KubeletReady    kubelet is posting ready status
lokomotive-worker-8        True     KubeletReady    kubelet is posting ready status
lokomotive-controller-1    True     KubeletReady    kubelet is posting ready status
lokomotive-controller-2    True     KubeletReady    kubelet is posting ready status
lokomotive-worker-21       True     KubeletReady    kubelet is posting ready status
lokomotive-worker-26       True     KubeletReady    kubelet is posting ready status
lokomotive-worker-25       True     KubeletReady    kubelet is posting ready status
lokomotive-worker-4        True     KubeletReady    kubelet is posting ready status
lokomotive-worker-5        True     KubeletReady    kubelet is posting ready status
lokomotive-worker-7        True     KubeletReady    kubelet is posting ready status
lokomotive-controller-0    True     KubeletReady    kubelet is posting ready status
lokomotive-worker-0        True     KubeletReady    kubelet is posting ready status
lokomotive-worker-11       True     KubeletReady    kubelet is posting ready status
lokomotive-worker-14       True     KubeletReady    kubelet is posting ready status
lokomotive-worker-24       True     KubeletReady    kubelet is posting ready status
lokomotive-worker-27       True     KubeletReady    kubelet is posting ready status
lokomotive-worker-29       True     KubeletReady    kubelet is posting ready status
lokomotive-worker-10       True     KubeletReady    kubelet is posting ready status
lokomotive-worker-2        True     KubeletReady    kubelet is posting ready status
lokomotive-worker-20       True     KubeletReady    kubelet is posting ready status
lokomotive-worker-23       True     KubeletReady    kubelet is posting ready status
W0304 05:36:49.324577  651090 warnings.go:70] v1 ComponentStatus is deprecated in v1.19+
Name      Status    Message              Error

```

**Comment by knrt10** [comment] 2021-03-04 06:50
Duplicate of #777

**Comment by invidian** [comment] 2021-03-15 18:37
Yep, will close as duplicate of #777.

**Closed by invidian** 2021-03-15 18:37 UTC
