### ISSUE TITLE
Cannot modify kubelet DaemonSet on a running cluster

### ISSUE THREAD

**Issue by johananl** [kinvolk/lokomotive#255] opened 2020-04-03 13:36 UTC
Modifying the kubelet DaemonSet on a running cluster results in kubelet pods being stuck at "Terminating" indefinitely. Possibly related to https://github.com/kinvolk/lokomotive/issues/110.

The setup I've used:

- Lokomotive `v0.1.0` on Packet
- Flatcar `2345.3.1`

Reproducing the problem:

1. Deploy a cluster with the above spec.
1. Run `kubectl -n kube-system edit ds kubelet`.
1. Modify something which requires pods to be re-created. I've added `--cloud-provider=external`.
1. Run `kubectl -n kube-system | grep kubelet` and check the pod status. The currently-updating pod should remain stuck at "Terminating".

**Comment by invidian** [comment] 2020-04-03 13:41
I think this is duplicate of https://github.com/kinvolk/lokomotive/issues/110.

**Comment by invidian** [comment] 2020-11-02 22:53
Updating kubelet DS now works with newest Flatcar stable, closing.

**Closed by invidian** 2020-11-02 22:53 UTC
Labels: bug
