### ISSUE TITLE
Make Terraform code accept taints and labels in complex type, not as string

### ISSUE THREAD

**Issue by invidian** [kinvolk/lokomotive#833] opened 2020-08-24 08:04 UTC
So we keep flexible format for longer and we can do the formatting to string on Terraform template level.

**Comment by knrt10** [comment] 2020-08-24 08:11
Related or duplicate of https://github.com/kinvolk/lokomotive/issues/489

**Comment by invidian** [comment] 2020-08-24 08:22
>Related or duplicate of #489

Related indeed, but #489 is about Go code and this one is about Terraform modules.

**Closed** 2020-10-08 11:21 UTC
Labels: kind/enhancement, technical-debt
