### ISSUE TITLE
Unify parameters for enabling monitoring

### ISSUE THREAD

**Issue by marga-kinvolk** [kinvolk/lokomotive#743] opened 2020-07-29 16:06 UTC
I'm deploying my first Lokomotive cluster and it's a bit confusing how each component has its unique set of parameters. With some things it makes sense because they are specific for that component. But for generic things like enabling monitoring, they could be unified under just one name.

What I've found so far:
* contour -> `enable_monitoring`
* external-dns -> `metrics`
* metallb -> `service_monitor`

I think `enable_monitoring` is probably the best out of those, but I don't really care which one is chosen.

**Comment by invidian** [comment] 2020-07-29 16:31
I'll close as duplicate of #407 :smile:

**Closed by invidian** 2020-07-29 16:31 UTC
