### ISSUE TITLE
Enable e2e tests for rook ceph

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#894] opened 2020-09-02 12:48 UTC
- Add a new pool of c2.mediums with at least 3 nodes.
- Install `rook-ceph` in ci.
- Add e2e package for pod verification.

**Comment by invidian** [comment] 2020-11-02 23:41
Partially done in #1084, also duplicate of #397.

**Closed by invidian** 2020-11-02 23:41 UTC
Labels: area/stability, area/storage, area/testing
