### ISSUE TITLE
deprecate rkt

### ISSUE THREAD

**Issue by vbatts** [kinvolk/lokomotive#811] opened 2020-08-17 18:52 UTC
As `rkt` upstream is now archived, let's switch to systemd-nspawn and/or docker.

[@alban had a branch](https://github.com/kinvolk/lokomotive-kubernetes/pull/100/files) for this that can serve as a reference.

**Comment by invidian** [comment] 2020-08-18 09:36
I'll close as a duplicate of #720.

**Closed by invidian** 2020-08-18 09:36 UTC

**Comment by vbatts** [comment] 2020-08-18 13:43
weird that didn't show up when i searched for "rkt" :thinking: 
thanks tho
