### ISSUE TITLE
Leaking Terraform processes when terminating a cluster operation

### ISSUE THREAD

**Issue by johananl** [kinvolk/lokomotive#329] opened 2020-04-23 12:02 UTC
When we Ctrl+C out of a `lokoctl cluster apply` operation (and likely `destroy`, too), the lokoctl process terminates without killing its child processes. As a result, depending on the exact stage in which Ctrl+C was pressed, one or more Terraform-related processes are left behind as orphans.

Steps to reproduce:

1. Run `lokoctl cluster apply -v` against any `.lokocfg` file.
1. Wait for Terraform to start creating infrastructure, then hit Ctrl+C.
1. Check for orphan processes: `ps -ef | grep terraform`.

Here is what I'm getting:

```
johannes 3061095    1421  0 13:52 pts/3    00:00:01 /usr/bin/terraform internal-plugin provisioner file
johannes 3061106 3061095  0 13:52 pts/3    00:00:00 /usr/bin/terraform internal-plugin provisioner file
johannes 3061107    1421  0 13:52 pts/3    00:00:00 /tmp/lk/assets/terraform/.terraform/plugins/linux_amd64/terraform-provider-template_v2.1.2_x4
johannes 3061125    1421  0 13:52 pts/3    00:00:01 /usr/bin/terraform internal-plugin provisioner remote-exec
johannes 3061137 3061125  0 13:52 pts/3    00:00:00 /usr/bin/terraform internal-plugin provisioner remote-exec
johannes 3061165    1421  0 13:52 pts/3    00:00:02 /tmp/lk/assets/terraform/.terraform/plugins/linux_amd64/terraform-provider-tls_v2.1.1_x4
johannes 3061179    1421  0 13:52 pts/3    00:00:00 /tmp/lk/assets/terraform/.terraform/plugins/linux_amd64/terraform-provider-local_v1.4.0_x4
johannes 3061195    1421  0 13:52 pts/3    00:00:00 /home/johannes/.terraform.d/plugins/terraform-provider-ct_v0.4.0
johannes 3061212    1421  0 13:52 pts/3    00:00:00 /tmp/lk/assets/terraform/.terraform/plugins/linux_amd64/terraform-provider-packet_v2.7.5_x4
johannes 3061228    1421  0 13:52 pts/3    00:00:00 /tmp/lk/assets/terraform/.terraform/plugins/linux_amd64/terraform-provider-null_v2.1.2_x4
```

The orphan processes stay in memory indefinitely, though thankfully it doesn't seem like they keep executing Terraform operations in this state.

We should most likely implement a proper cleanup procedure which we always run in response to a SIGINT.

**Comment by invidian** [comment] 2020-04-24 09:40
I wonder if this is a duplicate of #45? How they differ?

**Comment by johananl** [comment] 2020-04-29 12:55
https://github.com/kinvolk/lokomotive/issues/45 is likely the solution to this issue. However, this issue reports a concrete problem created by us not handling the signal.

**Comment by ipochi** [comment] 2020-06-03 17:49
Found out that `terraform apply` handles the interrupts but `terraform init` doesn't and this behavior is reflected the same in lokoctl as well.

An upstream issue has been filed for the same.

hashicorp/terraform#25118

**Closed** 2020-06-04 13:49 UTC
Labels: bug, priority/P2
