### ISSUE TITLE
`lokoctl health` does not fallback for kubeconfig

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#608] opened 2020-06-10 09:05 UTC
I don't have assets dir locally but in S3 and when I run following: 

```console
$ lokoctl health
Error: Kubeconfig "assets/cluster-assets/auth/kubeconfig" not found
Usage:
  lokoctl health [flags]

Flags:
  -h, --help   help for health

Global Flags:
      --kubeconfig string     Path to kubeconfig file, taken from the asset dir if not given, and finally falls back to ~/.kube/config
      --lokocfg string        Path to lokocfg directory or file (default "./")
      --lokocfg-vars string   Path to lokocfg.vars file (default "./lokocfg.vars")
```

It did not fallback to `~/.kube/config` as mentioned in the `--kubeconfig` flag description.

And same for `component apply` as well:

```console
$ lokoctl component apply
Applying component 'openebs-operator'...
FATA[0000] stat assets/cluster-assets/auth/kubeconfig: no such file or directory  args="[]" command="lokoctl component apply"
```

**Comment by invidian** [comment] 2020-06-10 09:08
This is expected behavior. If you have the valid configuration in working directory, it should be used. This is duplicate of #105, right?

**Comment by invidian** [comment] 2020-06-12 09:15
Turns out we pass kubeconfig path a lot:
```sh
$ git grep kubeconfig cli/ pkg/ | grep -v pkg/assets/generated_assets.go | grep kubeconfig | wc -l
55
```

The idea to solve this would to, to rather than passing kubeconfig **path**, we could pass the content of this file, which can be taken from anywhere. We could even validate it and pass it as some kind of generic client object, but this might be more difficult to use then.

**Comment by invidian** [comment] 2020-08-04 10:00
Oops, that shouldn't be closed. We are still missing #701.

**Comment by surajssd** [comment] 2020-08-06 13:37
Not just health but `lokoctl compont apply` also has fallback issues:

```console
$ lokoctl component apply metrics-server
FATA[0000] Error in finding kubeconfig file: open assets/cluster-assets/auth/kubeconfig: no such file
or directory  args="[metrics-server]" command="lokoctl component apply"
```

Even though I have the `~/.kube/config` file available:

```console
$ kubectl get nodes
NAME                   STATUS   ROLES    AGE   VERSION
foo-controller-0       Ready    <none>   90m   v1.18.6
foo-openebs-worker-0   Ready    <none>   89m   v1.18.6
```

**Comment by surajssd** [comment] 2020-08-06 13:38
@invidian should we at least get the fallback issues solved? Later we can look into extracting kubeconfig from the state?

**Comment by invidian** [comment] 2020-08-06 13:43
What do you mean by fallback? It shouldn't do any fallback if file is missing, as it may install things on a wrong cluster.

**Comment by surajssd** [comment] 2020-08-10 13:47
Then we should fix the kubeconfig flag help.

**Comment by invidian** [comment] 2020-08-10 13:51
>Then we should fix the kubeconfig flag help.

To mention if the cluster configuration is present in working directory? That make sense I guess :+1:

**Comment by invidian** [comment] 2020-08-10 16:27
It seems like too bit detail to put in the CLI flag description :|

**Comment by surajssd** [comment] 2020-08-11 07:47
We should completely remove the fallback to the global kubeconfig automatically and update the flag description.

**Comment by invidian** [comment] 2020-08-11 08:01
>We should completely remove the fallback to the global kubeconfig automatically and update the flag description.

If we remove that, we won't be able to install components on clusters managed with `kubeconfig contexts`, which IMO is a valuable feature. This does not apply to `health` sub-command of course. Do you suggest to have different behavior for `health` and `component`?

**Comment by invidian** [comment] 2020-08-20 18:28
@surajssd BTW current help message looks following:
```
$ ./lokoctl health --help
Get the health of a cluster

Usage:
  lokoctl health [flags]

Flags:
  -h, --help   help for health

Global Flags:
      --kubeconfig-file string   Path to a kubeconfig file. If empty, the following precedence order is used:
                                   1. Cluster asset dir when a lokocfg file is present in the current directory.
                                   2. KUBECONFIG environment variable.
                                   3. ~/.kube/config file.
      --lokocfg string           Path to lokocfg directory or file (default "./")
      --lokocfg-vars string      Path to lokocfg.vars file (default "./lokocfg.vars")
```

**Comment by invidian** [comment] 2020-08-20 19:01
Actually, I created #820 to get rid of this flag completely, simplifying the whole thing.

**Closed** 2020-09-03 11:13 UTC
Labels: bug
